### ISSUE TITLE
[BUG] - No translation found for CORE.UPDATES.ERRORS.FILEUPDATE

### ISSUE THREAD

**Issue by X3R0-FR** [CraftMyWebsite/cmw-core#393]
# 🐞️ Bug report

## Environment
- CMW Version: `alpha-05`
- PHP Version: `8.3`
- Browser: `Edge`
- Device Type: `Desktop`

## Bug Description
When we are in dev version and we try to update the cms, an error occurs but with a text without value

## Steps to Reproduce the Bug
1. Install DEV version
2. Update to last version
3. Observe error

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/6988e633-21c2-4546-ad37-da2a2923ea9d)

**Comment by Teyir** [comment]
In dev mode we can't update the CMS. It's a normal behaviour, but we need to check that before update checking.
